// Decompiled with JetBrains decompiler
// Type: Albion.Common.GameData.PlayerAttribute
// Assembly: Albion.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 8E9CFC81-AA34-4410-9004-379A07925CAB
// Assembly location: C:\Program Files (x86)\AlbionOnline\game\Albion-Online_Data\Managed\Albion.Common.dll

namespace Albion.Common.GameData
{
  public enum PlayerAttribute
  {
    HitpointsMax,
    HitpointsMaxBonus,
    HitpointsRegeneration,
    HitpointsRegenerationBonus,
    EnergyMax,
    EnergyMaxBonus,
    EnergyRegeneration,
    EnergyRegenerationBonus,
    CraftingFocusMax,
    CraftingFocusMaxBonus,
    CraftingFocusRegeneration,
    CraftingFocusRegenerationBonus,
    MoveSpeed,
    MoveSpeedBonus,
    MaxLoad,
    MaxLoadBonus,
    AttackDamage,
    PhysicalAttackDamageBonus,
    MagicAttackDamageBonus,
    AttackRangeBonus,
    AttackSpeedBonus,
    PhysicalSpellDamageBonus,
    MagicSpellDamageBonus,
    MagicCastTimeReductionRaw,
    MagicCastTimeReductionAdjusted,
    MagicCoolDownReductionRaw,
    MagicCoolDownReductionAdjusted,
    MagicCastingResilience,
    HealBonus,
    HealModifier,
    EnergyCostReduction,
    PhysicalArmor,
    MagicResistance,
    CrowdControlResistance,
    BalanceModifier,
    FocusFireModifier,
    HealingSicknessModifier,
    FocusFireProtectionPeneration,
    CraftTime,
    InstallTime,
    GatheringSpeed,
    GatheringYield,
    BonusDamageVsPlayers,
    BonusDefenseVsPlayers,
    BonusCCRVsPlayers,
    BonusCCDurationVsPlayers,
    BonusDamageVsMobs,
    BonusDefenseVsMobs,
    BonusCCRVsMobs,
    BonusCCDurationVsMobs,
    CrowdControlDiminishingReturn,
    CraftingQuality,
    CraftingFocusCostReduction,
    AbilityPower,
    AbilityPowerBonus,
    ItemPower,
    ThreatBonus,
    NumAttributes,
  }
}
